services:
  spark-master:
    image: spark-cluster:java11-spark3.2.1-hadoop3.2
    container_name: spark-master
    environment:
      - SPARK_WORKLOAD=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - 7080:8080
      - 7077:7077
    volumes:
      - ./:/opt/workspace

  spark-worker-1:
    image: spark-cluster:java11-spark3.2.1-hadoop3.2
    container_name: spark-worker-1
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    ports:
      - 7081:8081
    volumes:
      - ./:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-cluster:java11-spark3.2.1-hadoop3.2
    container_name: spark-worker-2
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    ports:
      - 7082:8081
    volumes:
      - ./:/opt/workspace
    depends_on:
      - spark-master

  jupyterlab:
    image: spark-jupyterlab:py3.9-jupyterlab3.2.9-spark3.2.1
    container_name: spark-jupyterlab
    ports:
      - 7888:8888
    volumes:
      - ./:/opt/workspace
